project_id: '1'
api_token: 5a82d40d38310f1cb2cc354eaeedaaf9d20b9b31f22de19244187b3d2a3e51aeac834afc349723e6
targets:
  - name: android
    files:
      - file: targets/%two_letters_code%/android.xml
        sources:
          - /main/test2.xml
base_path: .
base_url: 'https://montblanc.crowdin.com'
preserve_hierarchy: true
commit_message: 'Fix: New translations %original_file_name% from Crowdin Enterprise'
append_commit_message: false
files:
  - source: '*.md'
    translation: /folder/123%two_letters_code%.md
  - source: /*.xml
    translation: /%locale_with_underscore%/%original_file_name%
    translate_attributes: 0
    content_segmentation: 0
